# Generated by Django 5.0.14 on 2026-06-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frigate_event_id', models.CharField(max_length=100, unique=True)),
                ('camera_name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('top_score', models.FloatField(blank=True, null=True)),
                ('has_snapshot', models.BooleanField(default=False)),
                ('has_clip', models.BooleanField(default=False)),
                ('snapshot_url', models.CharField(blank=True, max_length=500)),
                ('thumbnail_url', models.CharField(blank=True, max_length=500)),
                ('clip_url', models.CharField(blank=True, max_length=500)),
                ('simple_description', models.TextField(blank=True)),
                ('ai_description', models.TextField(blank=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('false_alarm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['camera_name'], name='monitoring__camera__6b8ec6_idx'), models.Index(fields=['label'], name='monitoring__label_29ce5a_idx'), models.Index(fields=['started_at'], name='monitoring__started_9f2018_idx')],
            },
        ),
    ]
